# -*- coding: utf-8 -*-
"""bert for qa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9wnpnhpSNGFWTN52LSV2-8NekBJqPM8
"""

import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

import json
from datasets import Dataset
from transformers import AutoTokenizer

MODEL_NAME = "deepset/bert-base-cased-squad2"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

MAX_LENGTH = 384
DOC_STRIDE = 128

with open(
    r"/content/CUADv1.json",
    "r",
    encoding="utf-8"
) as f:

    cuad = json.load(f)

    records = []

for document in cuad["data"]:

    title = document.get("title", "")

    for paragraph in document["paragraphs"]:

        context = paragraph["context"]

        for qa in paragraph["qas"]:

            question = qa["question"]
            is_impossible = qa.get("is_impossible", False)

            answers = qa.get("answers", [])

            if answers:
                answer_text = answers[0]["text"]
                answer_start = answers[0]["answer_start"]
            else:
                answer_text = ""
                answer_start = 0

            records.append({
                "title": title,
                "context": context,
                "question": question,
                "answer_text": answer_text,
                "answer_start": answer_start,
                "is_impossible": is_impossible
            })

dataset = Dataset.from_list(records)

df = dataset.to_pandas()

dataset = dataset.train_test_split(
    test_size=0.1,
    seed=42
)

train_dataset = dataset["train"]
validation_dataset = dataset["test"]

def preprocess_function(examples):

    questions = [
        q.strip()
        for q in examples["question"]
    ]

    tokenized = tokenizer(
        questions,
        examples["context"],
        max_length=MAX_LENGTH,
        truncation="only_second",
        stride=DOC_STRIDE,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length"
    )

    sample_mapping = tokenized.pop(
        "overflow_to_sample_mapping"
    )

    offset_mapping = tokenized["offset_mapping"]

    start_positions = []
    end_positions = []

    for i, offsets in enumerate(offset_mapping):

        sample_index = sample_mapping[i]

        answer_start = examples["answer_start"][sample_index]
        answer_text = examples["answer_text"][sample_index]

        is_impossible = examples["is_impossible"][sample_index]

        # ------------------------------------------------
        # SQuAD2: no answer
        # ------------------------------------------------

        if is_impossible or not answer_text:

            cls_index = tokenized["input_ids"][i].index(
                tokenizer.cls_token_id
            )

            start_positions.append(cls_index)
            end_positions.append(cls_index)

            continue

        answer_end = answer_start + len(answer_text)

        # ------------------------------------------------
        # Find context token boundaries
        # ------------------------------------------------

        sequence_ids = tokenized.sequence_ids(i)

        context_start = 0

        while (
            context_start < len(sequence_ids)
            and sequence_ids[context_start] != 1
        ):
            context_start += 1

        context_end = len(sequence_ids) - 1

        while (
            context_end >= 0
            and sequence_ids[context_end] != 1
        ):
            context_end -= 1

        # Answer is outside this chunk
        if (
            offsets[context_start][0] > answer_start
            or offsets[context_end][1] < answer_end
        ):

            cls_index = tokenized["input_ids"][i].index(
                tokenizer.cls_token_id
            )

            start_positions.append(cls_index)
            end_positions.append(cls_index)

        else:

            # Find start token
            token_start = context_start

            while (
                token_start <= context_end
                and offsets[token_start][0] <= answer_start
            ):
                token_start += 1

            start_positions.append(token_start - 1)

            # Find end token
            token_end = context_end

            while (
                token_end >= context_start
                and offsets[token_end][1] >= answer_end
            ):
                token_end -= 1

            end_positions.append(token_end + 1)

    tokenized["start_positions"] = start_positions
    tokenized["end_positions"] = end_positions

    return tokenized

tokenized_train = train_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=train_dataset.column_names
)

tokenized_validation = validation_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=validation_dataset.column_names
)

from transformers import AutoModelForQuestionAnswering

model = AutoModelForQuestionAnswering.from_pretrained(
    MODEL_NAME
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./bert-cuad-qa",

    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=3e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    num_train_epochs=2,

    weight_decay=0.01,

    logging_steps=100,

    load_best_model_at_end=True,

    report_to="none"
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_validation
)

trainer.train()

trainer.save_model("./bert-cuad-qa")

tokenizer.save_pretrained("./bert-cuad-qa")



